on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

name: check-mnormt

jobs:
  g6tr-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-16.04,   r: '4.0', rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

   
          
      - name: Query dependencies
        run: |
          options(repos = c(CRAN = "https://cran.rstudio.com/", CLOUDYR = "http://cloudyr.github.io/drat"))
          install.packages(c('remotes', 'devtools', 'renv'))
        shell: Rscript {0}
          

      - name: Preconfiguration for installations
        run: |
          renv::install(c("remotes", "rcmdcheck", "devtools"))
        shell: Rscript {0}  
      - name: Install linux system dependencies with sysreqs
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          echo $sysreqs
          sudo -s eval "$sysreqs"
      - name: Install dependencies for the package - remotes
        run: |
          remotes::install_deps(pkgdir = ".", dependencies = c('Imports', 'Suggests'), repos = c(getOption("repos"), "http://cloudyr.github.io/drat")) 
        shell: Rscript {0} 
      - name: Install dependencies for the package - devtools
        run: |          
          devtools::install('.', quick = TRUE, dependencies = c('Imports', 'Suggests'))
        shell: Rscript {0}
      - name: Check the package
        run: rcmdcheck::rcmdcheck(path = ".", args = "--no-manual", error_on = "error", check_dir = "check")
        shell: Rscript {0}
      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
        
