on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

name: check-mnormt

jobs:
  g6tr-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-16.04,   r: '4.0', rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()    
          
      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}
          
      - uses: actions/cache@v2
        id: cache
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
            
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-2-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-2-

      - name: Preconfiguration for installations
        run: |
          renv::install(c("remotes", "rcmdcheck", "devtools"))
        shell: Rscript {0}  
      - name: Install linux system dependencies with sysreqs
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          echo $sysreqs
          sudo -s eval "$sysreqs"
      - name: Install dependencies for the package
        run: |
          renv::install("mnormt")
          renv::install("BiocManager")
          BiocManager::install("Biobase")
          installed.packages()
          remotes::install_deps(pkgdir = ".", dependencies = c('Imports', 'Suggests'), repos = c(getOption("repos"), "http://cloudyr.github.io/drat"))  
        shell: Rscript {0}
      - name: Check the package
        run: rcmdcheck::rcmdcheck(path = ".", args = "--no-manual", error_on = "error", check_dir = "check")
        shell: Rscript {0}
      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
        
